[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
if dein#util#_is_windows()
  let cmd = 'tools\\update-dll-mingw'
elseif dein#util#_is_cygwin()
  let cmd = 'make -f make_cygwin.mak'
elseif execute('gmake')
  let cmd = 'gmake'
else
  let cmd = 'make'
 endif
 let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'NeoTerm/NeoTerm'
if = "has('nvim')"
hook_add = '''
nnoremap <silent> ,rc :<C-u>TREPLSendFile<CR>
nnoremap <silent> ,rl :<C-u>TREPLSendLine<CR>
vnoremap <silent> ,rl :<C-u>TREPLSendSelection<CR>
nnoremap <silent> vt :<C-u>Ttoggle<CR>
nnoremap <silent> vs :terminal<CR>GAsource ~/.bash_profile<CR>
'''

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
nnoremap <silent> <Leader>fb :<C-u>Unite Buffer<CR>
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = 'unite.vim'
hook_add = '''
source ~/.config/nvim/plugins/vimfiler.rc.vim
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
source ~/.config/nvim/plugins/ale.rc.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'gregsexton/gitv'

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['ale', 'vim-gitbranch']
hook_add = '''
source ~/.config/nvim/plugins/lightline.rc.vim
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
nnoremap [nerdtree] <Nop>
nmap <C-h> [nerdtree]

nnoremap [nerdtree]<C-h> :<C-u>NERDTreeToggle<CR>
nnoremap [nerdtree]<C-f> :<C-u>NERDTreeFind<CR>

let NERDTreeWinSize =  44
'''

[[plugins]]
repo = 'sgur/vim-editorconfig'

[[plugins]]
repo = 'raphamorim/lucario'
hook_add = '''
autocmd ColorScheme * hi Visual ctermbg=90
autocmd ColorScheme * hi SpellCap ctermbg=3132
autocmd ColorScheme * hi SpellBad ctermbg=90
colorscheme lucario
'''

# TODO: 以下はlazyでも動きそうだけど動かなかったのでlazyについて調べて対応する
[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'rhysd/vim-textobj-ruby'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'tpope/vim-endwise'

# [[plugins]]
# repo = 'ludovicchabant/vim-gutentags'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'tasn/vim-tsx'

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'

[[plugins]]
repo = 'chase/vim-ansible-yaml'
hook_add = '''
let g:ansible_options = {'ignore_blank_lines': 0}
augroup filetypedetect
  au BufRead,BufNewFile *.yaml setfiletype ansible
  au BufRead,BufNewFile *.yml  setfiletype ansible
augroup END
'''

# colroscheme。採用していないのが気分で切り替える
# [[plugins]]
# repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'migrs/qfixhowm'
hook_add = '''
source ~/.config/nvim/plugins/qfixhowm.vim
'''

[[plugins]]
repo = 'thinca/vim-template'
hook_add = '''
let g:template_basedir = '~/.config'
let g:template_free_pattern = 'template'
'''

[[plugins]]
repo = 'rhysd/git-messenger.vim'

[[plugins]]
repo = 'preservim/tagbar'
hook_add = '''
nmap <F8> :<C-u>TagbarToggle<CR>
'''



